spring.application.name=akshaya-bank

# ── MySQL Local (change password if yours is different) ──────────────────────
spring.datasource.url=jdbc:mysql://rsts3n.h.filess.io:61001/akshayabank_mostlytree?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=akshayabank_mostlytree
spring.datasource.password=c46fdd8dca67d40964bb9be96f174126bd787e5b
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ── JPA ──────────────────────────────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ── JWT ───────────────────────────────────────────────────────────────────────
app.jwt.secret=AkshayaBankSuperSecretKey2024JWTTokenMin256BitsLongForHS256Algorithm!!
app.jwt.expiration=86400000

# ── Server ────────────────────────────────────────────────────────────────────
server.port=8080
server.servlet.context-path=/api

# ── CORS ──────────────────────────────────────────────────────────────────────
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000





spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
